apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "libraskefront.fullname" . | lower }}-app-config'
  labels:
    {{ include "libraskefront.labels" . | indent 4 }}
data:
{{ range $key, $val := .Values.libraskefront.appConfig }}
  {{ $key | quote }}:  {{ $val | quote }}
{{- end }}
